media:
  input: assets/img
  output: /assets/img

content:
  - name: posts
    label: Bài viết
    type: collection
    path: posts
    filename: "{fields.slug}.md"
    fields:
      - name: title
        label: Tiêu đề
        type: string
        required: true

      - name: slug
        label: Đường dẫn bài viết
        type: string
        required: true

      - name: date
        label: Ngày đăng
        type: date
        required: true

      - name: description
        label: Mô tả ngắn
        type: text

      - name: image
        label: Ảnh đại diện
        type: image

      - name: body
        label: Nội dung bài viết
        type: rich-text
